Repository astropy/package-template, pull requests merged in 2019-06, with the labels that each got.

#405 Updating the helpers versions to v2.0.10 and v3.2
  TEMPLATE_CHANGES.md
  cookiecutter.json
Labels: template

#388 Remove redundant Python version check
  {{ cookiecutter.package_name }}/setup.py
Labels: Ready-for-final-review, no-changelog-entry-needed

#408 Template cleanup travis
  .travis.yml
  {{ cookiecutter.package_name }}/.travis.yml
Labels: no-changelog-entry-needed, template

#409 Fixing some PEP8 for the rendered version
  {{ cookiecutter.package_name }}/.travis.yml
  {{ cookiecutter.package_name }}/setup.cfg
  {{ cookiecutter.package_name }}/{{ cookiecutter.module_name }}/__init__.py
  {{ cookiecutter.package_name }}/{{ cookiecutter.module_name }}/tests/test_example.py
Labels: no-changelog-entry-needed

#410 Adding ah_bootstrap even when the repo is not initailized
  hooks/post_gen_project.py
Labels: template

#411 Adding astropydev+numpydev job to the cron
  {{ cookiecutter.package_name }}/.travis.yml
Labels: template
